baseurl = "https://ghostnotepony.github.io/"
languageCode = "en"
title = "Ghost Note"
theme = "kiss"
copyright = "&copy; 2022 | Follow on <a rel=\"me\" href=\"https://equestria.social/@ghostnote\">Mastodon</a>"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]
includeContent = true # Includes whole content in rss
authorName = "Ghost Note" # Site author's full name

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Ghost Note" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.opengraph.twitter]
page = "ghostnotepony" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
#twitter = "ghostnotepony"
#rss = "index.xml"

[params.social.config]
#platforms = ["twitter","rss"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[params.sections_left]
url0 = ["https://twitter.com/ghostnotepony", "Twitter"]
url1 = ["https://twitch.tv/ghostnotepony",  "Twitch"]
url2 = ["https://ghostnotepony.github.io/index.xml",  "RSS"]
url3 = ["https://equestria.social/@ghostnote", "Mastodon"]
