baseURL = "https://jamestwilson.github.io/"
languageCode = "en-us"
title = "JTW"
theme = "hucore"
copyright = "&copy; 2018 | Follow on <a href=\"https://twitter.com/jamestheowilson\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = ""
keywords = ["family", "electric bass", "general thoughts", "ramblings", "brony"]
author = "JT Wilson"
sharingicons = true

[[params.social]]
title = "email"
fa_icon = "fa-envelope"
url = "mailto:jamestwilson@gmail.com"

[[params.social]]
url = "https://twitter.com/jamestheowilson"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://youtube.com/jamestheowilson"
fa_icon = "fa-youtube"

[[params.social]]
url = "https://twitch.tv/jamestheowilson"
fa_icon = "fa-twitch"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
