baseURL = "https://ghostnotepony.github.io/"
languageCode = "en-us"
title = "Ghost Note"
theme = "hucore"
copyright = "&copy; 2019 | Follow on <a href=\"https://twitter.com/ghostnotepony\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mojoaar/hucore\" target=\"_blank\">Hucore theme</a> & <a href=\"https://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = ""
keywords = ["family", "electric bass", "general thoughts", "ramblings", "brony"]
author = "Ghost Note"
sharingicons = true

[[params.social]]
title = "email"
fa_icon = "fa-envelope"
url = "mailto:jamestwilson@gmail.com"

[[params.social]]
url = "https://twitter.com/ghostnotepony"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://youtube.com/jamestheowilson"
fa_icon = "fa-youtube"

[[params.social]]
url = "https://twitch.tv/ghostnotepony"
fa_icon = "fa-twitch"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
